FROM rockylinux:9

WORKDIR /root/

RUN dnf upgrade --refresh -y && \
    dnf install git cmake dnf-utils -y && \
    dnf groupinstall 'Development Tools' -y && \
    dnf config-manager --set-enabled devel && \
    dnf config-manager --set-enabled crb && \
    dnf install -y epel-release

ARG VERSION=2.52.0
ENV VERSION=${VERSION}

ARG ARCH=x86-64-v2
ENV ARCH=${ARCH}

RUN echo "Building version $VERSION"

# Prepare to build libraries
RUN dnf install autoconf automake bzip2 bzip2-devel cmake freetype-devel gcc gcc-c++ git libtool make pkgconfig zlib-devel && \
    mkdir ~/ffmpeg_sources

# Build NASM
RUN cd ~/ffmpeg_sources && \
    curl -O -L https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2 && \
    tar xjvf nasm-2.15.05.tar.bz2 && \
    cd nasm-2.15.05 && \
    ./autogen.sh && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" && \
    make && \
    make install

# Build YASM
RUN cd ~/ffmpeg_sources && \
    curl -O -L https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz && \
    tar xzvf yasm-1.3.0.tar.gz && \
    cd yasm-1.3.0 && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" && \
    make && \
    make install

# Build libx264
RUN cd ~/ffmpeg_sources && \
    git clone --branch stable --depth 1 https://code.videolan.org/videolan/x264.git && \
    cd x264 && \
    PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" --enable-static && \
    make && \
    make install

# Build libx265
RUN cd ~/ffmpeg_sources && \
    git clone --branch stable --depth 2 https://bitbucket.org/multicoreware/x265_git && \
    cd ~/ffmpeg_sources/x265_git && \
    echo -e "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -march=$ARCH\")" >> ./CMakeLists.txt && \
    echo -e "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -march=$ARCH\")" >> ./CMakeLists.txt && \
    cd ~/ffmpeg_sources/x265_git/build/linux && \
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED:bool=off ../../source && \
    make && \
    make install

# Build libfdk-aac
RUN cd ~/ffmpeg_sources && \
    git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
    cd fdk-aac && \
    autoreconf -fiv && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --disable-shared && \
    make && \
    make install

# Build libmp3lame
RUN cd ~/ffmpeg_sources && \
    curl -O -L https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz && \
    tar xzvf lame-3.100.tar.gz && \
    cd lame-3.100 && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" --disable-shared --enable-nasm && \
    make && \
    make install

# Build libopus
RUN cd ~/ffmpeg_sources && \
    curl -O -L https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz && \
    tar xzvf opus-1.3.1.tar.gz && \
    cd opus-1.3.1 && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --disable-shared && \
    make && \
    make install

# Build libvpx
RUN cd ~/ffmpeg_sources && \
    git clone --depth 1 https://chromium.googlesource.com/webm/libvpx.git && \
    cd libvpx && \
    ./configure --extra-cflags="-march=$ARCH" --extra-cxxflags="-march=$ARCH" --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm && \
    make && \
    make install

# Build libaom-av1 - https://aomedia.googlesource.com/aom
RUN cd ~/ffmpeg_sources && \
    git clone https://aomedia.googlesource.com/aom && \
    echo -e "set(CMAKE_C_FLAGS \"${CMAKE_C_FLAGS} -march=$ARCH\")" >> ./CMakeLists.txt && \
    echo -e "set(CMAKE_CXX_FLAGS \"${CMAKE_CXX_FLAGS} -march=$ARCH\")" >> ./CMakeLists.txt && \
    mkdir ./aom_build && \
    cd ./aom_build && \
    cmake .. && \
    make && \
    make install

# Build ffmpeg
RUN cd ~/ffmpeg_sources && \
    curl -O -L https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
    tar xjvf ffmpeg-snapshot.tar.bz2 && \
    cd ffmpeg && \
    PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
      --prefix="$HOME/ffmpeg_build" \
      --pkg-config-flags="--static" \
      --extra-cflags="-I$HOME/ffmpeg_build/include -march=$ARCH" \
      --extra-cxxflags="-march=$ARCH" \
      --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
      --extra-libs=-lpthread \
      --extra-libs=-lm \
      --bindir="$HOME/bin" \
      --enable-gpl \
      --enable-libfdk_aac \
      --enable-libfreetype \
      --enable-libharfbuzz \
      --enable-libmp3lame \
      --enable-libopus \
      --enable-libvpx \
      --enable-libx264 \
      --enable-libx265 \
      --enable-libaom \
      --enable-nonfree
    make && \
    make install && \
    hash -d ffmpeg
